### ISSUE TITLE
Make the project popups more direct

### ISSUE THREAD

**Issue by bld2104** [CodeForPhilly/cfp-mockup#1]
Button that takes them to info page
Button that takes them to slack channel
smaller logo

**Comment by ZacharyRSmith** [comment]
dupe with #8 ?

**Comment by bld2104** [comment]
When a user clicks on a project image (PHLASK, Paws, etc.) a popup appears. Right now, there is a very faint "Learn More" link that takes them to the project page.

I am proposing that we replace this link with two buttons:

Button 1 is "Learn More" and takes them to the project page
Button 2 is "Get Involved" and the action is something that directly connects them with someone on the team or the team leader (not sure what exactly this action will be yet).
