### ISSUE TITLE
Create a "live" site

### ISSUE THREAD

**Issue by bld2104** [CodeForPhilly/cfp-mockup#10]
So stakeholders can see where we are with the project.

**Comment by themightychris** [comment]
I just enabled Github pages on the `main` branch for this repo, that should be enough to serve the site up somewhere as long as it's just static html: https://codeforphilly.github.io/cfp-mockup/

**Comment by bld2104** [comment]
@themightychris GAHHHH okay I didn't see this until after I loaded it somewhere else AND changed all the README files. Will this Github Page update automatically when the repo updates? If so I will ditch the one I created and change the readme to the one you created.

Please tag me in your response so I catch it.

**Comment by themightychris** [comment]
@bld2104 yep it will
