### ISSUE TITLE
design and code a sponsor page, link to it from > sponsor red icon

### ISSUE THREAD

**Issue by ZacharyRSmith** [CodeForPhilly/cfp-mockup#12]

**Comment by bld2104** [comment]
Content for Sponsor Page: https://docs.google.com/document/d/1qW6O6WndVvaepXVQSV9003k1piFos3OeT-eeEZftpmg/edit

Pictures for Sponsor Page: https://drive.google.com/drive/folders/1hltreJxmtMH-7DnE15Pzs2cbh9zHFEiC?usp=sharing
