### ISSUE TITLE
design a "how nonprofits can get help from us" page, link to it from > red icon

### ISSUE THREAD

**Issue by ZacharyRSmith** [CodeForPhilly/cfp-mockup#13]

**Comment by bld2104** [comment]
Link to Gitbook, & highlight that the steps are to fill out the intake form & email it to hello@codeforphilly.org

**Comment by bld2104** [comment]
https://codeforphilly.org/pages/project_guidelines

**Comment by wuh0o** [comment]
https://code-for-philly.gitbook.io/partnerships/creating-new-partnerships/first-steps
