### ISSUE TITLE
Fix Login Button on Menu?

### ISSUE THREAD

**Issue by bld2104** [CodeForPhilly/cfp-mockup#21]
Is it possible to:

1) once the user logs in, redirect them back to the new homepage and the login button disappears
2) Instead, show in the upper-right corner their image and name like we do in the current site?
3) Include the dropdown once they are logged in that allows them to manage their profile, logout, etc.

**Comment by ZacharyRSmith** [comment]
Question I forgot to ask: what is the purpose of logging in? I'm new to cfp, and haven't yet seen a reason to log in

**Comment by bld2104** [comment]
On 4/27 we decided to change this so that we are just putting login and sign up buttons on the new homepage and they won't change even if the user is logged in. Each just links to the same place the current login and signup buttons go to on the current site.
