### ISSUE TITLE
Move header and footer to separate html files

### ISSUE THREAD

**Issue by bld2104** [CodeForPhilly/cfp-mockup#26]
And import them into page files

header.html
footer.html

**Comment by ZacharyRSmith** [comment]
without a compiler, i think this would require async fetching of these separate html files. That would add lag, and getting things to load in the right order might be tricky

what are the benefits of this?

**Comment by wuh0o** [comment]
we talked about how if we're going to have multiple pages for the site, it would be better to not have to copy/paste the header and footer code into each page

i brought up the issue, but not sure what the best way is to go about doing this

**Comment by ZacharyRSmith** [comment]
i agree copy/paste isn't ideal

i'm not sure, either

i guess we could add a compiler

Could be a build tool

Could be as simple as a script that replaces some annotations in src/index.html and other "real" pages with the header and footer, then outputs to output/index.html or such. We edit src files. Run script. Website runs off of output files

ok i'll think about this
