### ISSUE TITLE
Rethink the Menu Items

### ISSUE THREAD

**Issue by bld2104** [CodeForPhilly/cfp-mockup#29]
Issue 1: Current website has a button for Slack

On the current homepage, once you login, the "Join us" button changes to "Chat with us" and you can get to Slack. I (Barb) personally never thought this was intuitive.

change "Community/Connect" to "Slack":
- Remove the dropdown from that menu
- Add "member directory" to the "About" dropdown.
- remove the forum link

other:
- Change "Projects 101" to "Start a Project"
- Relink "Start a Project" to https://code-for-philly.gitbook.io/partnerships/creating-new-partnerships/first-steps
- Add "Volunteer" and "Sponsor" to the "Get Involved" menu dropdown
- Change "Active Projects" to "Find a Project"
- Remove "Weekly Meetups" link

**Comment by bld2104** [comment]
@wuh0o is going to also set up a card sort for our conversation possibly.

**Comment by bld2104** [comment]
@bld2104 is going to double check with leadership team why they wanted menu put back this way and if we need to think about anythinig.

**Comment by ZacharyRSmith** [comment]
remaining TODOs: "Add "Volunteer" and "Sponsor" to the "Get Involved" menu dropdown"
