### ISSUE TITLE
Enhance Code Angel's Volunteer Page

### ISSUE THREAD

**Issue by bld2104** [CodeForPhilly/cfp-mockup#35]

**Comment by wuh0o** [comment]
design: https://codeforphilly.slack.com/files/U01TG9DPBEX/F022H4Z8DN0/volunteer-page-02.jpg

- https://docs.google.com/document/d/1r0dXsnsSKS8r8BYLNMfhN3-q6a6q7kXmf0SwaIkWtUU/edit > link to all the content, includes the text, video, and images for the page
- most of the colors used are taken from the website
- dark background #212529
- light background #f8f9fa
- black text #000000
- gray text #6c757d
- red color #dc3545
- blue color (links) #2388e4
- line dividers in the sections use the same gray color but with lower opacity
- fonts are also taken from website: headings > Montserrat, text content > Roboto Slab

**Comment by ZacharyRSmith** [comment]
notes to self on TODOs:
- replace `<hr />`s (which has semantic meaning unsuitable for this case)
- add icons at intro
- enhance colors
- enhance collapsed sections
    - add carets
- add shadows to each step's card

~links are colored red instead of blue. Idk if we want to change that?~ going with red

**Comment by wuh0o** [comment]
if links are red, then we should probably keep them red for consistency
i didn't know what color to make the links so i chose a blue color
