### ISSUE TITLE
Explore API/Database Calls for Content

### ISSUE THREAD

**Issue by bld2104** [CodeForPhilly/cfp-mockup#5]
Can we pull data from the Laddr system to populate HTML or even another CMS like WordPress?

Deliverable: a writeup of what that would look like, issues with this idea, etc.

**Comment by themightychris** [comment]
Pretty much every page you can visit on laddr can be grabbed in JSON format either via an `Accept: application/json` header or `?format=json` query param, e.g.: 

- https://codeforphilly.org/projects?format=json

That might be a good way to mock up content

However, when new HTML templates are installed into the site, they'll have access to all data while they're rendered on the backend and don't need to make an XHR call after loading in most cases -- speeding up loading and improving SEO.

Templating schemes could easily be converted during installation, but also it might be better to just statically copy+paste content from laddr for purposes of building out the static mockups, and then just replace the static content with backend template variables during installation. Unless there's really a big interest in building out the whole site in vue or react components, it's probably not worth cooking up a whole frontend templating scheme just to populate initial dynamic content

**Comment by ZacharyRSmith** [comment]
@themightychris 

we'd like to call https://codeforphilly.org/search?q=foo&include=recordTitle%2CrecordURL&format=json

is this possible? We're getting a CORS err, but i don't see the sever's Access-Control-Allow-Origin: https://github.com/CodeForPhilly/laddr/search?q=Access-Control-Allow-Origin

**Comment by themightychris** [comment]
@ZacharyRSmith CORS config is outside the application codebase, in the instance configuration. I've enabled CORS from `*` for now, but it might be good to tighten that up in the future to something like `['localhost', 'codeforphilly.github.io']`

Also FYI, you can also use the param `&summary=1` to get shorter "summary" serializations back -- these serializations are designed to be optimal for things like listing search results. This is great for find-as-you-type result display as project descriptions and user bios can contain a lot of content. It doesn't look like projects/project-updates have any fields marked with `includeInSummary` yet -- but whatever fields you want to show in search results are the ones that should be. After you have a design together we can look at what fields you're using and then set up to switch to summary serializations
