### ISSUE TITLE
Remove unused/missing assets

### ISSUE THREAD

**Issue by themightychris** [CodeForPhilly/cfp-mockup#64]
- Remove `dist/vidbg.css` ref in header and any other VideoJS bits
- Remove `assets/mail/**` files and any references to old contact form
- Look into all 404s shown in browser console / remove any other old bits we can delete
- Can anything under `assets/img/` be removed?

**Comment by ZacharyRSmith** [comment]
`Can anything under assets/img/ be removed?` yes. I remember seeing some stock photos
